name: codium-insiders
adopt-info: codium-insiders
summary: Code editing. Redefined.
description: |
  Binary releases of Code Insiders without branding/telemetry/licensing

base: core20
grade: stable
confinement: classic
compression: lzo

parts:
  codium-insiders:
    plugin: nil
    override-build: |
      set -eu
      ARCHITECTURE=$(dpkg --print-architecture)
      # Get GitHub releases
      wget --quiet https://api.github.com/repos/VSCodium/vscodium-insiders/releases -O latest.json
      VERSION=$(jq -r 'sort_by(.tag_name)|last.tag_name' latest.json)
      DEB_URL=$(jq -r 'map(select(.tag_name == "'"$VERSION"'"))|first.assets[].browser_download_url|select(endswith("'"_$ARCHITECTURE.deb"'"))' latest.json)
      DEB=$(basename "${DEB_URL}")
      # Downloading .deb"
      wget "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      # Unpacking .deb"
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
      rm -f latest.json
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      # Set version
      snapcraftctl set-version "$(echo "${VERSION}" | sed 's|\-insider||')"
      # Correct path to icon.
      sed -i 's|Icon=vscodium-insiders|Icon=${SNAP}/usr/share/pixmaps/vscodium-insiders.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/codium-insiders.desktop
      sed -i 's|Exec=/usr/share/codium-insiders/codium-insiders|Exec=codium-insiders|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/codium-insiders.desktop
      sed -i 's|Icon=vscodium-insiders|Icon=${SNAP}/usr/share/pixmaps/vscodium-insiders.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/codium-insiders-url-handler.desktop
    build-packages:
      - wget
      - jq
    stage-packages:
      - ca-certificates
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo2
      - libcanberra-gtk3-module
      - libcurl3-gnutls
      - libcurl3-nss
      - libcurl4
      - libdrm2
      - libgbm1
      - libgl1
      - libglib2.0-0
      - libgtk-3-0
      - libibus-1.0-5
      - libnss3
      - libpango-1.0-0
      - libsecret-1-0
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxkbcommon0
      - libxkbfile1
      - libxrandr2
      - libxss1
      - locales-all
      - packagekit-gtk3-module
      - xdg-utils
    prime:
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man

  electron-launch:
    after:
      - codium-insiders
    plugin: dump
    source: snap/local

  cleanup:
    after:
      - electron-launch
    plugin: nil
    build-snaps:
      - core20
    override-prime: |
      set -eux
      for snap in "core20"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      patchelf --print-rpath $SNAPCRAFT_PRIME/usr/share/codium-insiders/chrome_crashpad_handler

apps:
  codium-insiders:
    command: electron-launch $SNAP/usr/share/codium-insiders/bin/codium-insiders --no-sandbox
    common-id: codium-insiders.desktop

  url-handler:
    command: electron-launch $SNAP/usr/share/codium-insiders/bin/codium-insiders --open-url --no-sandbox
