version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: insider
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 1
  - package-ecosystem: npm
    directory: /font-size
    target-branch: insider
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      all-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 1
