version: 2

updates:

  - package-ecosystem: github-actions
    directory: /
    target-branch: insider
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
    allow:
      - dependency-type: all

  - package-ecosystem: npm
    directory: /font-size
    target-branch: insider
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: '@types/node'
        versions: [ '>=23.0.0' ]
