rules:
  superfluous-actions:
    ignore:
      # allows `svenstaro/upload-release-action` action
      - publish-insider-linux.yml:482
      - publish-insider-linux.yml:546
      - publish-stable-linux.yml:487
      - publish-stable-linux.yml:551
