FROM ubuntu:20.04

RUN apt update && \
    DEBIAN_FRONTEND="noninteractive" \
    apt install -y \
        gcc-10 \
        g++-10 \
        libkrb5-dev \
        libx11-dev \
        libxkbfile-dev \
        libsecret-1-dev \
        qemu-user \
        && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
