name: codium
adopt-info: codium
summary: Code editing. Redefined.
description: |
  Binary releases of Code without branding/telemetry/licensing

base: core22
grade: stable
confinement: classic
compression: lzo

parts:
  codium:
    plugin: nil
    override-build: |
      set -eu
      # Get .deb url
      wget --quiet https://api.github.com/repos/VSCodium/vscodium/releases -O latest.json
      VERSION=$( jq -r 'sort_by(.tag_name)|last.tag_name' latest.json )
      DEB_URL=$( jq -r 'map(select(.tag_name == "'"${VERSION}"'"))|first.assets[].browser_download_url|select(endswith("'"_${CRAFT_TARGET_ARCH}.deb"'"))' latest.json )
      DEB_NAME=$( basename "${DEB_URL}" )
      # Downloading .deb
      wget "${DEB_URL}" -O "${CRAFT_PART_INSTALL}/${DEB_NAME}"
      # Unpacking .deb
      dpkg -x "${CRAFT_PART_INSTALL}/${DEB_NAME}" "${CRAFT_PART_INSTALL}"
      # Clean up
      rm -f latest.json
      rm -f "${CRAFT_PART_INSTALL}/${DEB_NAME}"
      # Set version
      craftctl set version=${VERSION}
      # Prepare GUI
      mkdir -p "${CRAFT_PART_INSTALL}/meta/gui"
      cp "${CRAFT_PART_INSTALL}/usr/share/codium/resources/app/resources/linux/code.png" "${CRAFT_PART_INSTALL}/meta/gui/codium.png"
      # Update paths
      # sed -i 's|Exec=/usr/share/codium/codium|Exec=codium --force-user-env|g' "${CRAFT_PART_INSTALL}/usr/share/applications/codium.desktop"
      # sed -i 's|Exec=/usr/share/codium/codium|Exec=codium --force-user-env|g' "${CRAFT_PART_INSTALL}/usr/share/applications/codium-url-handler.desktop"
      sed -i 's|Icon=vscodium|Icon=${SNAP}/meta/gui/codium.png|g' "${CRAFT_PART_INSTALL}/usr/share/applications/codium.desktop"
      sed -i 's|Icon=vscodium|Icon=${SNAP}/meta/gui/codium.png|g' "${CRAFT_PART_INSTALL}/usr/share/applications/codium-url-handler.desktop"
    build-packages:
      - wget
      - jq
    stage-packages:
      - libasound2
      - libatk1.0-0
      - libcairo2
      - libgbm1
      - libglib2.0-0
      - libgtk-3-0
      - libnss3
      - libpango-1.0-0
      - libsecret-1-0
      - libtiff5
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxkbcommon0
      - libxkbfile1
      - libxrandr2
      - libxss1
    prime:
      - -etc
      - -var
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/codium/chrome-sandbox
    build-attributes:
      - enable-patchelf
    override-prime: |
      set -eux
      craftctl default
      for snap in "core22"; do
        cd "/snap/${snap}/current/"
        find . -type f,l -name "*.so*" -exec bash -c "rm -rf ${CRAFT_PRIME}/{}*" \;
      done

  electron-launch:
    after:
      - codium
    plugin: dump
    source: snap/local/bin

apps:
  codium:
    command: usr/share/codium/bin/codium --no-sandbox
    command-chain:
      - electron-launch
    desktop: usr/share/applications/codium.desktop
    common-id: codium.desktop

  url-handler:
    command: usr/share/codium/bin/codium --open-url --no-sandbox
    command-chain:
      - electron-launch
    desktop: usr/share/applications/codium-url-handler.desktop
