/**
 * Mock Design Sidecar Adapter - Cursor ING
 *
 * Implements the Open Design sidecar interface with mock/local responses.
 * No API keys, no network calls.
 *
 * Interface based on Open Design contracts (Apache 2.0).
 */

/** Task states from Open Design contracts */
export type TaskState = 'queued' | 'starting' | 'running' | 'succeeded' | 'failed' | 'cancelled';

export interface TaskStatus {
  id: string;
  state: TaskState;
  label?: string;
  detail?: string;
  startedAt?: number;
  updatedAt?: number;
  endedAt?: number;
}

export interface DesignSkill {
  name: string;
  description: string;
  triggers: string[];
  mode: string;
  platform: string;
}

export interface DesignSystem {
  id: string;
  name: string;
  description: string;
}

export interface GenerateRequest {
  prompt: string;
  skill: string;
  designSystem: string;
  visualDirection?: string;
  options?: Record<string, string>;
}

export interface GenerateResult {
  taskId: string;
  status: TaskStatus;
  prompt: string;
  skill: string;
  designSystem: string;
  files: { path: string; content: string }[];
  planSteps: string[];
  selfCheck: { passed: boolean; notes: string[] };
  timestamp: number;
}

/** Sidecar interface — all implementations must support these operations */
export interface DesignSidecar {
  /** Start the sidecar daemon */
  start(): Promise<void>;
  /** Stop the sidecar daemon */
  stop(): Promise<void>;
  /** Get current status */
  status(): { running: boolean; provider: string };
  /** List available design skills */
  listSkills(): DesignSkill[];
  /** List available design systems */
  listDesignSystems(): DesignSystem[];
  /** Generate a new design artifact */
  generate(request: GenerateRequest): Promise<GenerateResult>;
  /** Read a previously generated project */
  readProject(projectId: string): Promise<GenerateResult | undefined>;
  /** Open preview for an artifact */
  openPreview(taskId: string): Promise<void>;
}

/** Mock implementation for Phase 1 */
export class MockDesignSidecar implements DesignSidecar {
  private running = true;
  private projects: Map<string, GenerateResult> = new Map();

  async start(): Promise<void> {
    this.running = true;
    console.log('Design Sidecar started (mock)');
  }

  async stop(): Promise<void> {
    this.running = false;
    console.log('Design Sidecar stopped (mock)');
  }

  status() {
    return { running: this.running, provider: 'mock-local' };
  }

  listSkills(): DesignSkill[] {
    return [
      { name: 'landing-page', description: 'Marketing/product landing page', triggers: ['landing page', 'homepage'], mode: 'prototype', platform: 'web' },
      { name: 'dashboard', description: 'Admin/analytics dashboard', triggers: ['dashboard', 'admin panel'], mode: 'prototype', platform: 'desktop' },
      { name: 'app-screen', description: 'Mobile/desktop app screen', triggers: ['app screen', 'mobile app'], mode: 'prototype', platform: 'responsive' },
      { name: 'slide-deck', description: 'Presentation slides', triggers: ['slides', 'presentation'], mode: 'document', platform: 'desktop' },
      { name: 'prototype', description: 'Interactive web prototype', triggers: ['prototype', 'mockup'], mode: 'prototype', platform: 'web' },
    ];
  }

  listDesignSystems(): DesignSystem[] {
    return [
      { id: 'minimal', name: 'Minimal', description: 'Clean, whitespace-heavy design' },
      { id: 'vercel', name: 'Vercel', description: 'Modern, geometric SaaS aesthetic' },
      { id: 'apple', name: 'Apple', description: 'Human interface guidelines style' },
      { id: 'agentic', name: 'Agentic', description: 'AI-first industrial UI' },
      { id: 'linear', name: 'Linear', description: 'High-performance productivity look' },
    ];
  }

  async generate(request: GenerateRequest): Promise<GenerateResult> {
    const taskId = `task-${Date.now()}`;
    const timestamp = Date.now();

    // Mock generation — returns a scaffold HTML artifact
    const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>${request.prompt}</title>
<style>body{font-family:system-ui;margin:0;padding:40px;background:#fafbfc;color:#1f2328;}
h1{font-size:28px;margin-bottom:8px;}
p{color:#656d76;font-size:14px;}
.card{background:#fff;border:1px solid #d8dee4;border-radius:8px;padding:20px;margin:16px 0;}
</style></head>
<body>
<h1>${request.skill} — Generated Artifact</h1>
<p>Prompt: "${request.prompt}" | Design System: ${request.designSystem} | Skill: ${request.skill}</p>
<div class="card"><strong>Phase 1 Mock</strong><br>This is a scaffold artifact. Real generation will use Open Design daemon in Phase 2.</div>
<div class="card"><strong>Generated by</strong>: Cursor ING Design Studio (mock-local)</div>
</body></html>`;

    const result: GenerateResult = {
      taskId,
      status: { id: taskId, state: 'succeeded', startedAt: timestamp - 1000, endedAt: timestamp },
      prompt: request.prompt,
      skill: request.skill,
      designSystem: request.designSystem,
      files: [{ path: 'index.html', content: html }],
      planSteps: ['Analyze prompt', 'Select design tokens', 'Assemble components', 'Verify accessibility'],
      selfCheck: { passed: true, notes: ['Mock generation — no real AI provider used'] },
      timestamp
    };

    this.projects.set(taskId, result);
    return result;
  }

  async readProject(projectId: string): Promise<GenerateResult | undefined> {
    return this.projects.get(projectId);
  }

  async openPreview(taskId: string): Promise<void> {
    console.log(`Opening preview for task: ${taskId}`);
  }
}
