extends:
  - "@commitlint/config-conventional"
rules:
  body-max-line-length:
    - 2
    - always
    - 200
  type-enum:
    - 2
    - always
    -
      - build
      - ci
      - docs
      - enhance
      - feat
      - fix
      - perf
      - refactor
      - remodel
      - revert
      - style
      - test
      - vcs
