name: Lint - ecformat

on:
  push:
    branches:
      - master
      - insider
  pull_request:
    branches:
      - "**"

permissions: {}

jobs:
  ecformat:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install ecformat
        run: |
          curl --remote-name https://codeberg.org/api/packages/BaumiCoder/generic/ecformat_bin/0.2.0/ecformat-x86_64-unknown-linux-gnu.tar.gz

          echo "e790f3d3a478c3c9db154727ccc2547f7affceec2b8e0f794c7b9d8a132bf65a  ecformat-x86_64-unknown-linux-gnu.tar.gz" | sha256sum --check --strict

          tar -xzf ecformat-x86_64-unknown-linux-gnu.tar.gz

          sudo cp ecformat /usr/local/bin/

          rm -f ecformat ecformat-x86_64-unknown-linux-gnu.tar.gz

      - name: Run ecformat
        run: |
          ecformat check --verbose --ignore-file .ecformat_ignore
