name: TEST - Anylinux AppImage

on:
  workflow_dispatch: {}

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  APP_NAME: VSCodium
  BINARY_NAME: codium
  DISABLE_UPDATE: yes
  GH_REPO_PATH: ${{ github.repository }}
  GITHUB_BRANCH: ${{ github.ref_name }}
  ORG_NAME: ${{ github.repository_owner }}
  OS_NAME: linux
  VSCODE_QUALITY: stable

permissions: {}

jobs:
  compile:
    runs-on: ubuntu-22.04
    env:
      VSCODE_ARCH: x64
    outputs:
      BUILD_SOURCEVERSION: ${{ env.BUILD_SOURCEVERSION }}
      MS_COMMIT: ${{ env.MS_COMMIT }}
      MS_TAG: ${{ env.MS_TAG }}
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@a2861a8b8538f49cf2850980acccf6b05a1b2ae4 # v2.0
        with:
          version: 10
          platform: x64

      - name: Setup Node.js environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc

      - name: Setup Python 3
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.11"

      - name: Install libkrb5-dev
        run: sudo apt-get update -y && sudo apt-get install -y libkrb5-dev

      - name: Clone VSCode repo
        run: ./get_repo.sh

      - name: Build
        env:
          SHOULD_BUILD: yes
          SHOULD_BUILD_REH: no
          SHOULD_BUILD_REH_WEB: no
        run: ./build.sh

      - name: Compress vscode artifact
        run: |
          find vscode -type f -not -path "*/node_modules/*" -not -path "vscode/.build/node/*" -not -path "vscode/.git/*" > vscode.txt
          echo "vscode/.build/extensions/node_modules" >> vscode.txt
          echo "vscode/.git" >> vscode.txt
          tar -czf vscode.tar.gz -T vscode.txt

      - name: Upload vscode artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: vscode
          path: ./vscode.tar.gz
          retention-days: 1

  build:
    needs:
      - compile
    runs-on: ubuntu-latest
    container:
      image: vscodium/vscodium-linux-build-agent:focal-x64
    env:
      BUILD_SOURCEVERSION: ${{ needs.compile.outputs.BUILD_SOURCEVERSION }}
      MS_COMMIT: ${{ needs.compile.outputs.MS_COMMIT }}
      MS_TAG: ${{ needs.compile.outputs.MS_TAG }}
      RELEASE_VERSION: ${{ needs.compile.outputs.RELEASE_VERSION }}
      VSCODE_ARCH: x64
    outputs:
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install GH
        run: ./build/linux/install_gh.sh

      - name: Install dependencies
        run: ./build/linux/deps.sh

      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1

      - name: Download vscode artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: vscode

      - name: Build
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_arch: x64
        run: ./build/linux/package_bin.sh

      - name: Upload VSCode binary (for anylinux-appimage)
        run: tar -czf vscode-bin.tar.gz -C "VSCode-linux-${VSCODE_ARCH}" .

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: vscode-bin-x64
          path: ./vscode-bin.tar.gz
          retention-days: 1

  anylinux-appimage:
    needs:
      - build
    runs-on: ubuntu-latest
    container: ghcr.io/pkgforge-dev/archlinux:latest
    env:
      RELEASE_VERSION: ${{ needs.build.outputs.RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Preparing Container
        uses: pkgforge-dev/anylinux-setup-action@0964f2258d6c93d1391359978dde081fd8b3c6af # v2

      - name: Download vscode binary artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: vscode-bin-x64

      - name: Install Dependencies
        run: /bin/sh ./build/anylinux-appimage/get-dependencies.sh

      - name: Make AppImage
        run: /bin/sh ./build/anylinux-appimage/make-appimage.sh

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: AppImage-anylinux
          path: dist/
          retention-days: 3